import xbmc
import xbmcgui

if xbmc.getCondVisibility('Control.HasFocus(8001)') == 1:
	xbmc.executebuiltin("ClearProperty(Widget.Top250,Home)")
	xbmc.executebuiltin("SetProperty(Widget.Type," + xbmc.getInfoLabel("$INFO[Container(9000).ListItem.Property(WidgetType)]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Cover," + xbmc.getInfoLabel("$VAR[HomeWidget8001CoverVar]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.DiscArt," + xbmc.getInfoLabel("$VAR[HomeWidget8001DiscArtVar]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.DiscArtFake," + xbmc.getInfoLabel("$VAR[HomeWidget8001FakeDiscArtVar]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Top250," + xbmc.getInfoLabel("$INFO[Container(8001).ListItem.Top250]") + "),home")
	xbmc.executebuiltin("SetProperty(Widget.Title," + xbmc.getInfoLabel("$VAR[HomeWidget8001LabelVar]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.TitleSub," + xbmc.getInfoLabel("$VAR[HomeWidget8001SubLabelVar]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Year," + xbmc.getInfoLabel("$VAR[HomeWidget8001FlagsYear]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.FlagsRating," + xbmc.getInfoLabel("$VAR[HomeWidget8001FlagsRating]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.FlagsStudio," + xbmc.getInfoLabel("$VAR[HomeWidget8001FlagsStudios]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.FlagsSource," + xbmc.getInfoLabel("$VAR[HomeWidget8001FlagsSource]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.FlagsResolution," + xbmc.getInfoLabel("$VAR[HomeWidget8001FlagsResolution]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.FlagsAspect," + xbmc.getInfoLabel("$VAR[HomeWidget8001FlagsAspect]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.FlagsAudio," + xbmc.getInfoLabel("$VAR[HomeWidget8001FlagsAudio]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.FlagsAudioChannels," + xbmc.getInfoLabel("$VAR[HomeWidget8001FlagsAudioChannels]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.FlagsCC," + xbmc.getInfoLabel("$VAR[HomeWidget8001FlagsCC]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Resolution," + xbmc.getInfoLabel("$INFO[Container(8001).ListItem.VideoResolution]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Icon1," + xbmc.getInfoLabel("$VAR[HomeWidget8001Icon1Var]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Info1," + xbmc.getInfoLabel("$VAR[HomeWidget8001Info1Var]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Icon2," + xbmc.getInfoLabel("$VAR[HomeWidget8001Icon2Var]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Info2," + xbmc.getInfoLabel("$VAR[HomeWidget8001Info2Var]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Plot," + xbmc.getInfoLabel("$VAR[HomeWidget8001PlotVar]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.FolderPath," + xbmc.getInfoLabel("$INFO[Container(8001).ListItem.FolderPath]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.FilePath," + xbmc.getInfoLabel("$INFO[Container(8001).ListItem.FileNameAndPath]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Resume," + xbmc.getInfoLabel("$INFO[Container(8001).ListItem.PercentPlayed]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Trailer," + xbmc.getInfoLabel("$INFO[Container(8001).ListItem.Trailer]") + ")")
	xbmc.executebuiltin("XBMC.ActivateWindow(1199)")		
	xbmc.executebuiltin("XBMC.Control.SetFocus(8052)")

if xbmc.getCondVisibility('Control.HasFocus(8002)') == 1:
	xbmc.executebuiltin("SetProperty(Widget.Type," + xbmc.getInfoLabel("$INFO[Container(9000).ListItem.Property(WidgetType2)]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Cover," + xbmc.getInfoLabel("$VAR[HomeWidget8002CoverVar]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.DiscArt," + xbmc.getInfoLabel("$VAR[HomeWidget8002DiscArtVar]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.DiscArtFake," + xbmc.getInfoLabel("$VAR[HomeWidget8002FakeDiscArtVar]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Top250," + xbmc.getInfoLabel("$INFO[Container(8002).ListItem.Top250]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Title," + xbmc.getInfoLabel("$VAR[HomeWidget8002LabelVar]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.TitleSub," + xbmc.getInfoLabel("$VAR[HomeWidget8002SubLabelVar]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Year," + xbmc.getInfoLabel("$VAR[HomeWidget8002FlagsYear]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.FlagsRating," + xbmc.getInfoLabel("$VAR[HomeWidget8002FlagsRating]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.FlagsStudio," + xbmc.getInfoLabel("$VAR[HomeWidget8002FlagsStudios]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.FlagsSource," + xbmc.getInfoLabel("$VAR[HomeWidget8002FlagsSource]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.FlagsResolution," + xbmc.getInfoLabel("$VAR[HomeWidget8002FlagsResolution]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.FlagsAspect," + xbmc.getInfoLabel("$VAR[HomeWidget8002FlagsAspect]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.FlagsAudio," + xbmc.getInfoLabel("$VAR[HomeWidget8002FlagsAudio]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.FlagsAudioChannels," + xbmc.getInfoLabel("$VAR[HomeWidget8002FlagsAudioChannels]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.FlagsCC," + xbmc.getInfoLabel("$VAR[HomeWidget8002FlagsCC]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Resolution," + xbmc.getInfoLabel("$INFO[Container(8002).ListItem.VideoResolution]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Icon1," + xbmc.getInfoLabel("$VAR[HomeWidget8002Icon1Var]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Info1," + xbmc.getInfoLabel("$VAR[HomeWidget8002Info1Var]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Icon2," + xbmc.getInfoLabel("$VAR[HomeWidget8002Icon2Var]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Info2," + xbmc.getInfoLabel("$VAR[HomeWidget8002Info2Var]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Plot," + xbmc.getInfoLabel("$VAR[HomeWidget8002PlotVar]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.FolderPath," + xbmc.getInfoLabel("$INFO[Container(8002).ListItem.FolderPath]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.FilePath," + xbmc.getInfoLabel("$INFO[Container(8002).ListItem.FileNameAndPath]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Resume," + xbmc.getInfoLabel("$INFO[Container(8002).ListItem.PercentPlayed]") + ")")
	xbmc.executebuiltin("SetProperty(Widget.Trailer," + xbmc.getInfoLabel("$INFO[Container(8002).ListItem.Trailer]") + ")")
	xbmc.executebuiltin("XBMC.ActivateWindow(1199)")		
	xbmc.executebuiltin("XBMC.Control.SetFocus(8052)")